// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportLeague.Data;

#nullable disable

namespace SportLeague.Data.Migrations
{
    [DbContext(typeof(SportLeagueDbContext))]
    [Migration("20260511175037_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportLeague.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Score")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            AwayTeamId = 2,
                            GameDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            Score = "2-1"
                        },
                        new
                        {
                            GameId = 2,
                            AwayTeamId = 3,
                            GameDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            Score = "1-3"
                        },
                        new
                        {
                            GameId = 3,
                            AwayTeamId = 1,
                            GameDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            Score = "2-2"
                        },
                        new
                        {
                            GameId = 4,
                            AwayTeamId = 3,
                            GameDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            Score = "1-0"
                        });
                });

            modelBuilder.Entity("SportLeague.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FullName = "Vinicius Junior",
                            Position = "Forward",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 2,
                            FullName = "Jude Bellingham",
                            Position = "Midfielder",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 3,
                            FullName = "Robert Lewandowski",
                            Position = "Forward",
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 4,
                            FullName = "Pedri",
                            Position = "Midfielder",
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 5,
                            FullName = "Erling Haaland",
                            Position = "Forward",
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 6,
                            FullName = "Kevin De Bruyne",
                            Position = "Midfielder",
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("SportLeague.Entities.PlayerGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GoalsScored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("PlayerGames");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            GameId = 1,
                            GoalsScored = 1,
                            MinutesPlayed = 90
                        },
                        new
                        {
                            PlayerId = 2,
                            GameId = 1,
                            GoalsScored = 1,
                            MinutesPlayed = 90
                        },
                        new
                        {
                            PlayerId = 3,
                            GameId = 2,
                            GoalsScored = 1,
                            MinutesPlayed = 90
                        },
                        new
                        {
                            PlayerId = 4,
                            GameId = 2,
                            GoalsScored = 0,
                            MinutesPlayed = 85
                        },
                        new
                        {
                            PlayerId = 5,
                            GameId = 3,
                            GoalsScored = 2,
                            MinutesPlayed = 90
                        },
                        new
                        {
                            PlayerId = 6,
                            GameId = 3,
                            GoalsScored = 0,
                            MinutesPlayed = 90
                        },
                        new
                        {
                            PlayerId = 1,
                            GameId = 4,
                            GoalsScored = 1,
                            MinutesPlayed = 90
                        },
                        new
                        {
                            PlayerId = 5,
                            GameId = 4,
                            GoalsScored = 0,
                            MinutesPlayed = 90
                        });
                });

            modelBuilder.Entity("SportLeague.Entities.PlayerProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<decimal>("Height_cm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight_kg")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProfileId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");

                    b.HasData(
                        new
                        {
                            ProfileId = 1,
                            Height_cm = 176m,
                            Nationality = "Brazil",
                            PlayerId = 1,
                            Weight_kg = 73m
                        },
                        new
                        {
                            ProfileId = 2,
                            Height_cm = 186m,
                            Nationality = "England",
                            PlayerId = 2,
                            Weight_kg = 75m
                        },
                        new
                        {
                            ProfileId = 3,
                            Height_cm = 185m,
                            Nationality = "Poland",
                            PlayerId = 3,
                            Weight_kg = 80m
                        },
                        new
                        {
                            ProfileId = 4,
                            Height_cm = 174m,
                            Nationality = "Spain",
                            PlayerId = 4,
                            Weight_kg = 70m
                        },
                        new
                        {
                            ProfileId = 5,
                            Height_cm = 194m,
                            Nationality = "Norway",
                            PlayerId = 5,
                            Weight_kg = 88m
                        },
                        new
                        {
                            ProfileId = 6,
                            Height_cm = 181m,
                            Nationality = "Belgium",
                            PlayerId = 6,
                            Weight_kg = 76m
                        });
                });

            modelBuilder.Entity("SportLeague.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Founded")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            City = "Madrid",
                            Founded = 1902,
                            TeamName = "Real Madrid"
                        },
                        new
                        {
                            TeamId = 2,
                            City = "Barcelona",
                            Founded = 1899,
                            TeamName = "Barcelona"
                        },
                        new
                        {
                            TeamId = 3,
                            City = "Manchester",
                            Founded = 1880,
                            TeamName = "Manchester City"
                        });
                });

            modelBuilder.Entity("SportLeague.Entities.Game", b =>
                {
                    b.HasOne("SportLeague.Entities.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportLeague.Entities.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("SportLeague.Entities.Player", b =>
                {
                    b.HasOne("SportLeague.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportLeague.Entities.PlayerGame", b =>
                {
                    b.HasOne("SportLeague.Entities.Game", "Game")
                        .WithMany("PlayerGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportLeague.Entities.Player", "Player")
                        .WithMany("PlayerGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SportLeague.Entities.PlayerProfile", b =>
                {
                    b.HasOne("SportLeague.Entities.Player", "Player")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("SportLeague.Entities.PlayerProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SportLeague.Entities.Game", b =>
                {
                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("SportLeague.Entities.Player", b =>
                {
                    b.Navigation("PlayerGames");

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("SportLeague.Entities.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
