// <auto-generated />
using System;
using EFCoreFinal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreFinal.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523062040_Rename_Name_Columns")]
    partial class Rename_Name_Columns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreFinal.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Books"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Sports"
                        });
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("date");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            CustomerName = "John Smith",
                            Email = "john.smith@email.com",
                            LastLoginDate = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            City = "Los Angeles",
                            CustomerName = "Sarah Johnson",
                            Email = "sarah.johnson@email.com",
                            LastLoginDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0102"
                        },
                        new
                        {
                            Id = 3,
                            City = "Chicago",
                            CustomerName = "Michael Brown",
                            Email = "michael.brown@email.com",
                            LastLoginDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0103"
                        },
                        new
                        {
                            Id = 4,
                            City = "Houston",
                            CustomerName = "Emily Davis",
                            Email = "emily.davis@email.com",
                            LastLoginDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0104"
                        },
                        new
                        {
                            Id = 5,
                            City = "Phoenix",
                            CustomerName = "David Wilson",
                            Email = "david.wilson@email.com",
                            LastLoginDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0105"
                        });
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 48,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 195,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 73,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 27,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 23,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 39,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 96,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 58,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            AvailableQuantity = 35,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            AvailableQuantity = 42,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            AvailableQuantity = 79,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            AvailableQuantity = 55,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            AvailableQuantity = 65,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            AvailableQuantity = 38,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            AvailableQuantity = 48,
                            ProductId = 15
                        });
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("date");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Discount = 10m,
                            LastLoginDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderAmount = 199.97m,
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Discount = 15m,
                            LastLoginDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderAmount = 369.96m,
                            Status = "Processing"
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            Discount = 5m,
                            LastLoginDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderAmount = 249.97m,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            Discount = 0m,
                            LastLoginDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderAmount = 129.98m,
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 4,
                            Discount = 20m,
                            LastLoginDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderAmount = 389.97m,
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 5,
                            Discount = 8m,
                            LastLoginDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderAmount = 149.98m,
                            Status = "Delivered"
                        });
                });

            modelBuilder.Entity("EFCoreFinal.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            PricePerUnit = 79.99m,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            PricePerUnit = 12.99m,
                            ProductId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            PricePerUnit = 45.99m,
                            ProductId = 4,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            PricePerUnit = 55.99m,
                            ProductId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            PricePerUnit = 19.99m,
                            ProductId = 7,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            PricePerUnit = 59.99m,
                            ProductId = 8,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            PricePerUnit = 34.99m,
                            ProductId = 10,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            PricePerUnit = 24.99m,
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            PricePerUnit = 25.99m,
                            ProductId = 13,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 5,
                            PricePerUnit = 89.99m,
                            ProductId = 14,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 6,
                            PricePerUnit = 49.99m,
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 6,
                            PricePerUnit = 39.99m,
                            ProductId = 6,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Price = 79.99m,
                            ProductName = "Wireless Headphones",
                            Quantity = 50,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Price = 12.99m,
                            ProductName = "USB-C Cable",
                            Quantity = 200,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Price = 49.99m,
                            ProductName = "Portable Charger",
                            Quantity = 75,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Price = 45.99m,
                            ProductName = "C# Programming Guide",
                            Quantity = 30,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Price = 55.99m,
                            ProductName = "Entity Framework Core in Action",
                            Quantity = 25,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Price = 39.99m,
                            ProductName = "Clean Code",
                            Quantity = 40,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Price = 19.99m,
                            ProductName = "Cotton T-Shirt",
                            Quantity = 100,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Price = 59.99m,
                            ProductName = "Denim Jeans",
                            Quantity = 60,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Price = 129.99m,
                            ProductName = "Winter Jacket",
                            Quantity = 35,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Price = 34.99m,
                            ProductName = "LED Desk Lamp",
                            Quantity = 45,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Price = 24.99m,
                            ProductName = "Plant Pot Set",
                            Quantity = 80,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Price = 29.99m,
                            ProductName = "Wall Clock",
                            Quantity = 55,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Price = 25.99m,
                            ProductName = "Yoga Mat",
                            Quantity = 70,
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Price = 89.99m,
                            ProductName = "Dumbbell Set",
                            Quantity = 40,
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Price = 99.99m,
                            ProductName = "Running Shoes",
                            Quantity = 50,
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SupplierName = "TechCorp Electronics"
                        },
                        new
                        {
                            Id = 2,
                            SupplierName = "Global Publishing Inc."
                        },
                        new
                        {
                            Id = 3,
                            SupplierName = "Fashion World Ltd."
                        },
                        new
                        {
                            Id = 4,
                            SupplierName = "Home Essentials Co."
                        },
                        new
                        {
                            Id = 5,
                            SupplierName = "Sports Gear Supply"
                        });
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Inventory", b =>
                {
                    b.HasOne("EFCoreFinal.Entities.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Order", b =>
                {
                    b.HasOne("EFCoreFinal.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EFCoreFinal.Entities.OrderItem", b =>
                {
                    b.HasOne("EFCoreFinal.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreFinal.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Product", b =>
                {
                    b.HasOne("EFCoreFinal.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreFinal.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("EFCoreFinal.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
