<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MiniBank.Data\MiniBank.Data.csproj" />
	  <ProjectReference Include="..\MiniBank.Repository\MiniBank.Repository.csproj" />
	  <ProjectReference Include="..\MiniBank.Service\MiniBank.Service.csproj" />
	</ItemGroup>

</Project>