<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="MailKit" Version="4.17.0" />
	  <PackageReference Include="Mapster" Version="10.0.10" />
	  <PackageReference Include="Mapster.DependencyInjection" Version="10.0.10" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
	  <PackageReference Include="MimeKit" Version="4.17.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Company524.Domain\Company524.Domain.csproj" />
	</ItemGroup>

</Project>
