// <auto-generated />
using System;
using Company524.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company524.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613170252_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company524.API.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CategoryName = "Books"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CategoryName = "Home & Garden"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CategoryName = "Sports"
                        });
                });

            modelBuilder.Entity("Company524.API.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("date");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            City = "New York",
                            CustomerName = "John Smith",
                            Email = "john.smith@email.com",
                            LastLoginDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0101"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            City = "Los Angeles",
                            CustomerName = "Sarah Johnson",
                            Email = "sarah.johnson@email.com",
                            LastLoginDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0102"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            City = "Chicago",
                            CustomerName = "Michael Brown",
                            Email = "michael.brown@email.com",
                            LastLoginDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0103"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            City = "Houston",
                            CustomerName = "Emily Davis",
                            Email = "emily.davis@email.com",
                            LastLoginDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0104"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000005"),
                            City = "Phoenix",
                            CustomerName = "David Wilson",
                            Email = "david.wilson@email.com",
                            LastLoginDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            PhoneNumber = "+1-555-0105"
                        });
                });

            modelBuilder.Entity("Company524.API.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            CustomerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Discount = 10m,
                            OrderAmount = 199.97m,
                            OrderDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            CustomerId = new Guid("44444444-0000-0000-0000-000000000002"),
                            Discount = 15m,
                            OrderAmount = 369.96m,
                            OrderDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Processing"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000003"),
                            CustomerId = new Guid("44444444-0000-0000-0000-000000000003"),
                            Discount = 5m,
                            OrderAmount = 249.97m,
                            OrderDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000004"),
                            CustomerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Discount = 0m,
                            OrderAmount = 129.98m,
                            OrderDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000005"),
                            CustomerId = new Guid("44444444-0000-0000-0000-000000000004"),
                            Discount = 20m,
                            OrderAmount = 389.97m,
                            OrderDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000006"),
                            CustomerId = new Guid("44444444-0000-0000-0000-000000000005"),
                            Discount = 8m,
                            OrderAmount = 149.98m,
                            OrderDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Delivered"
                        });
                });

            modelBuilder.Entity("Company524.API.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000001"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000001"),
                            PricePerUnit = 79.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000001"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000002"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000001"),
                            PricePerUnit = 12.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000002"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000003"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000002"),
                            PricePerUnit = 45.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000004"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000004"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000002"),
                            PricePerUnit = 55.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000005"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000005"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000003"),
                            PricePerUnit = 19.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000007"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000006"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000003"),
                            PricePerUnit = 59.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000008"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000007"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000004"),
                            PricePerUnit = 34.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000010"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000008"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000004"),
                            PricePerUnit = 24.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000011"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000009"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000005"),
                            PricePerUnit = 25.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000013"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000010"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000005"),
                            PricePerUnit = 89.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000014"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000011"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000006"),
                            PricePerUnit = 49.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000012"),
                            OrderId = new Guid("55555555-0000-0000-0000-000000000006"),
                            PricePerUnit = 39.99m,
                            ProductId = new Guid("33333333-0000-0000-0000-000000000006"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Company524.API.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Price = 79.99m,
                            ProductName = "Wireless Headphones",
                            Quantity = 50,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Price = 12.99m,
                            ProductName = "USB-C Cable",
                            Quantity = 200,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Price = 49.99m,
                            ProductName = "Portable Charger",
                            Quantity = 75,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Price = 45.99m,
                            ProductName = "C# Programming Guide",
                            Quantity = 30,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Price = 55.99m,
                            ProductName = "Entity Framework Core in Action",
                            Quantity = 25,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Price = 39.99m,
                            ProductName = "Clean Code",
                            Quantity = 40,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Price = 19.99m,
                            ProductName = "Cotton T-Shirt",
                            Quantity = 100,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Price = 59.99m,
                            ProductName = "Denim Jeans",
                            Quantity = 60,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Price = 129.99m,
                            ProductName = "Winter Jacket",
                            Quantity = 35,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000004"),
                            Price = 34.99m,
                            ProductName = "LED Desk Lamp",
                            Quantity = 45,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000004"),
                            Price = 24.99m,
                            ProductName = "Plant Pot Set",
                            Quantity = 80,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000004"),
                            Price = 29.99m,
                            ProductName = "Wall Clock",
                            Quantity = 55,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000013"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000005"),
                            Price = 25.99m,
                            ProductName = "Yoga Mat",
                            Quantity = 70,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000014"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000005"),
                            Price = 89.99m,
                            ProductName = "Dumbbell Set",
                            Quantity = 40,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000015"),
                            CategoryId = new Guid("11111111-0000-0000-0000-000000000005"),
                            Price = 99.99m,
                            ProductName = "Running Shoes",
                            Quantity = 50,
                            SupplierId = new Guid("22222222-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("Company524.API.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            SupplierName = "TechCorp Electronics"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            SupplierName = "Global Publishing Inc."
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            SupplierName = "Fashion World Ltd."
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            SupplierName = "Home Essentials Co."
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            SupplierName = "Sports Gear Supply"
                        });
                });

            modelBuilder.Entity("Company524.API.Models.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Company524.API.Entities.Order", b =>
                {
                    b.HasOne("Company524.API.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Company524.API.Entities.OrderItem", b =>
                {
                    b.HasOne("Company524.API.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company524.API.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Company524.API.Entities.Product", b =>
                {
                    b.HasOne("Company524.API.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company524.API.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Company524.API.Models.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Company524.API.Models.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company524.API.Models.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Company524.API.Models.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company524.API.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Company524.API.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Company524.API.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
