// <auto-generated />
using ITStepClass.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITStepClass.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509173252_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITStepClass.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Design"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cyber Security"
                        });
                });

            modelBuilder.Entity("ITStepClass.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Name = "UI/UX"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Name = "Network Security"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Name = "Ethical Hacking"
                        });
                });

            modelBuilder.Entity("ITStepClass.Entities.Subject", b =>
                {
                    b.HasOne("ITStepClass.Entities.Department", "Department")
                        .WithMany("Subject")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITStepClass.Entities.Department", b =>
                {
                    b.Navigation("Subject");
                });
#pragma warning restore 612, 618
        }
    }
}
